site_name: Watsonx.data and Milvus RAG Demonstration
# theme:
#   name: material
nav:
  - Introduction: "wxd-introduction.md"
  - Getting Started:
    - Requesting an image: "wxd-reference-techzone.md"
    - Accessing the reservation: "wxd-reference-access.md"
    - Available Ports: "wxd-reference-ports.md"
    - Userids and Passwords: "wxd-reference-passwords.md"
    - Documentation: "wxd-reference-documentation.md"
  - Lab Instructions:
    - Main Menu: "wxd-demo-menu.md" 
    - Overview: "wxd-demo-intro.md"
    - RAG: "wxd-demo-rag.md"
    - Import Documents: "wxd-demo-import.md"
    - Vectorize Documents: "wxd-demo-vectorize.md"
    - Query LLM: "wxd-demo-queryllm.md"
    - Manage LLM: "wxd-demo-managellm.md"
    - Diagnostics: "wxd-demo-diagnostics.md"
    - Log File: "wxd-demo-log.md"
    - Sample LLM Queries: "wxd-demo-examples.md"
    - Db2 Vectors: "wxd-db2-vectors.md"
    - Support: "wxd-demo-support.md"
  - Appendix: 
    - Watsonx.data Overview:
      - Watsonx UI Overview: "wxd-intro-watsonui.md"
      - Infrastructure Manager: "wxd-intro-infrastructure.md"
      - Data Manager: "wxd-intro-datamanager.md"
      - Query Workspace: "wxd-intro-queryworkspace.md"
      - Milvus: "wxd-milvus.md"
    - Disclaimer: "wxd-disclaimer.md"
    - Acknowledgements: "wxd-acknowledgements.md"

  # Copyright
copyright: Copyright &copy; 2025 IBM 

# Theme
theme:
  name: material
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  logo: wxd-images/IBM_logo®_rev_RGB.png  
  palette:
    scheme: default
    primary: black
    accent: black

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences    
  - pymdownx.keys
  - pymdownx.tasklist:
      custom_checkbox: true 
